services:
  - type: web
    name: NEZUKO-V2
    env: node
    branch: main
    repo: https://github.com/W-i-z-z-k-i-d/NEZUKO-V2.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: Qá´œá´‡á´‡É´-Ná´‡á´¢á´œá´‹á´;Gá´á´…-Zá´‡É´Éªá´›êœ±á´œ;https://graph.org/file/3879cf1910f65bd8457d7.jpg
      - key: ALWAYS_ONLINE
        value: true
      - key: AUTO_STATUS_VIEWS
        value: true
      - key: AUDIO_DATA
        value: Gá´á´…-Zá´‡É´Éªá´›êœ±á´œ;Qá´œá´‡á´‡É´-Ná´‡á´¢á´œá´‹á´;https://graph.org/file/3879cf1910f65bd8457d7.jpg
      - key: PREFIX
        value: ^
      - key: WORK_TYPE
        value: private
      - key: SERVER
        value: render
      - key: CAPTION
        value: ğğ„ğ™ğ”ğŠğ ğŒğƒğŸŒˆ
      - key: STICKER_DATA
        value: ğ˜‡ğ—²ğ—»ğ—¶ğ˜ğ˜€ğ˜‚;ğ—»ğ—²ğ˜‡ğ˜‚ğ—¸ğ—¼
      - key: SUDO
        value: 917025673121
      - key: SERVERURL
        value:
      - key: DATABASE_URL
        sync: false
      - key: LOGS
        value: true
